export const UPDATE_PRODUCT_DETAILS = 'UPDATE_PRODUCT_DETAILS';
export const UPDATE_PRODUCT_CURRENT = 'UPDATE_PRODUCT_CURRENT';
export const UPDATE_PRODUCTS_LIST_BY_SEARCH = 'UPDATE_PRODUCTS_LIST_BY_SEARCH';
export const UPDATE_PRODUCTS_LIST_BY_SORT = 'UPDATE_PRODUCTS_LIST_BY_SORT';
export const ADD_NEW_PRODUCT = 'ADD_NEW_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

